apiVersion: v1              # Set apiVersion to v1
kind: Service               # Set kind to Service
metadata:                   # Set metadata for this manifest
  name: karsajobs-ui
  labels:
    app: karsajobs-app
spec:                       # Define the spec of this manifest
  selector:                 # Define the selector of this manifest
    tier: frontend
  ports:                    # Define the ports of this manifest
  - port: 8000              # Use the defined port on package.json
    name: frontend          # Set name as frontend
  type: NodePort            # Set the service type to NodePort
