apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: karsajobs-app
        tier: frontend
    spec:
      containers:
        - name: karsajobs-ui
          image: ghcr.io/limglenaldin/karsajobs-ui:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
          env:
          - name: VUE_APP_BACKEND
            value: http://127.0.0.1:35079
