apiVersion: v1                                        # Set apiVersion to v1
kind: Secret                                          # Set kind to Secret
metadata:                                             # Set metadata for this manifest
  name: karsajobs-db-creds
  namespace: karsajobs-app-ns
type: Opaque                                          # Set type to Opaque
data:                                                 # Define the data in base64
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
